package "memcached"
package "libsasl2-dev"
package "libmemcached-dev"
package "libmemcached-dbg"
package "libcurl4-gnutls-dev"
package "unzip"
package "zip"
package "imagemagick"
package "libxslt-dev"
package "libpq-dev"
package "libxml2-dev"
package "libxslt-dev"
package "libsasl2-dev"

